apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: say-hi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: say-hi
    spec:
      containers:
      - name: say-hi
        image: quay.io/bshelton229/say-hi:latest
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: say-hi
                key: port
          - name: ENV_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: say-hi
                key: message
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 80
