apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: say-hi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: say-hi
      annotations:
        version: "1"
    spec:
      containers:
      - name: say-hi
        image: quay.io/bshelton229/say-hi:latest
        resources:
          limits:
            memory: "200Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/my-config
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: say-hi
                key: port
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: say-hi
