apiVersion: v1
kind: Pod
metadata:
  name: say-hi-investigate
spec:
  restartPolicy: Never
  containers:
  - name: say-hi
    image: bshelton229/say-hi:broken
    volumeMounts:
    - name: config-volume
      mountPath: /etc/my-config
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: say-hi
            key: port
      - name: ENV_MESSAGE
        valueFrom:
          configMapKeyRef:
            name: say-hi
            key: message
    ports:
    - containerPort: 80

  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: say-hi
